# MPLAB IDE generated this makefile for use with GNU make.
# Project: osc1khz.mcp
# Date: Wed May 14 15:06:55 2014

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

ocs1Khz.cof : ocs1Khz.o
	$(CC) /p16F877A "ocs1Khz.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"ocs1Khz.cof" /M"ocs1Khz.map" /W /x

ocs1Khz.o : ocs1Khz.asm C:/Program\ Files/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "ocs1Khz.asm" /l"ocs1Khz.lst" /e"ocs1Khz.err" /d__DEBUG=1

clean : 
	$(CC) "ocs1Khz.o" "ocs1Khz.hex" "ocs1Khz.err" "ocs1Khz.lst" "ocs1Khz.cof"

